# Copyright 2025 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: svelte
  namespace: svelte-ui
spec:
  network:
    expose:
      - service: ui
        selector:
          app: ui
        host: svelte
        gateway: tenant
        port: 3000
    allow:
      - direction: Ingress
        remoteGenerated: IntraNamespace
      - direction: Egress
        remoteGenerated: IntraNamespace
