# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

tasks:
  - name: compliment
    description: "Give a compliment"
    actions:
      - cmd: |
          # List of compliments
          compliments='
          - you are smart
          - you are stylish
          - you are an inspiration
          - you are the coolest
          - you are a unicorn
          '
          # Get a random item from the list and send it!
          selected=$(echo "$compliments" | uds zarf tools yq 'shuffle | .[0]')
          echo "${selected}!!!"
        description: "Giving a compliment"
