tasks:
  - name: compliment
    description: "Give a compliment"
    actions:
      - cmd: |
          # List of compliments
          compliments=(
             "you are smart"
             "you are stylish"
             "you are an inspiration"
             "you are #1 in my book"
             "you are a unicorn"
          )
          # Get a random index from the array and send it!
          random_index=$(( RANDOM % ${#compliments[@]} ))
          echo "${compliments[$random_index]}!!!"
        description: "Giving a compliment"