apiVersion: v1
kind: Service
metadata:
  labels:
    app: ui
  name: ui
  namespace: svelte-ui
spec:
  ports:
    - name: "3000"
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: ui
  type: ClusterIP
