# Copyright 2025 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

variables:
  # zarf package
  podinfo:
    PODINFO_REPLICAS: 4
##    PODINFO_UI_LOGO: ""
